### PR TITLE
peng/468 password confirm

### PR DESCRIPTION
**Pull request by nylira**
- [x] add password confirmation field to NiSessionSignUp
- [x] add password confirmation field to NiSessionImport
- [x] add unit tests for new code

### Issue
closes: #468

### Screenshots
screen shot 2018-03-06 at 1 43 07 pm
screen shot 2018-03-06 at 2 01 43 pm

### CODE REVIEW

**Comment by nylira** [comment]
It appears the integration test is failing?

```
# logs in
unhandledRejection { Error: element ("#app-content") still not existing after 5000ms
  message: 'element ("#app-content") still not existing after 5000ms',
  type: 'WaitUntilTimeoutError' }
```

**Comment by faboweb** [comment]
Could you please recheck, that this an actual bug and not a semantic error? -> Is `#app-content` actual showing following the log in steps in the E2E tests? Probably they need to be updated with the new password confirmation step.

**Comment by nylira** [comment]
Haven't had time to look at this. It seems like you're probably correct @faboweb, the extra password confirmation step has to be mocked in the e2e test

**Comment by faboweb** [comment]
will be green after #543

**Comment by jolesbi** [comment]
@nylira @faboweb still failing...

**Comment by faboweb** [comment]
different error. I check it out.

**Comment by faboweb** [comment]
#magic

**Pull request merged**
