### PR TITLE
fedekunze/1409 fix bond amount

### LINKED ISSUE #1409: Can’t increase amount to undelegate (add the number) when 0 < bond < 1
Follow up of https://github.com/cosmos/voyager/pull/1367#pullrequestreview-161516834

### PR DESCRIPTION
**Pull request by fedekunze**
Closes #1409

_Description:_

**Note**, I can't test it since I can't receive tokens on the local-testnet due to bech32 prefix issues

❤️ Thank you!

---

* [x] Added entries in `CHANGELOG.md` with issue # and GitHub username
* [x] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

**Comment by faboweb** [comment]
can't you use the mocked testnet for this?

**Comment by faboweb** [comment]
Blocked because unable to test because of https://github.com/cosmos/cosmos-sdk/issues/2654

**Comment by jbibla** [comment]
codecov says the tests have decreased by `0.01%` ...

**Comment by faboweb** [comment]
In total but the touched code has full coverage. This is why the total coverage is not a required check.

**Comment by jbibla** [comment]
@faboweb why did you reject my approval instead of merging?

**Comment by faboweb** [comment]
This happens automatically when you merge in new code. This wasn't the disapprove your approval. ;)

**Pull request merged**
