### PR TITLE
Windows/Linux "About" window

### LINKED ISSUE #767: Cosmos Voyager "about" doesn't work on Windows
UI Version: 0.6.1

Description:

Clicking "Cosmos Voyager" "About Cosmos Voyager" doesn't show anything on Windows.

### PR DESCRIPTION
**Pull request by mappum**
Closes #767 

This makes the "About Cosmos Voyager" menu item functional on Windows and Linux (it now redirects to Preferences as suggested by @nylira, although we will need to add the app version to that page).

### CODE REVIEW

**Comment by faboweb** [comment]
Sounds good. :) But coverage is missing ;)

**Comment by faboweb** [comment]
@mappum

**Comment by mappum** [comment]
Fixed the test coverage

**Comment by faboweb** [comment]
Also, should we wait until #907 is done?

**Comment by okwme** [comment]
#916

**Pull request merged**
