### PR TITLE
David-Jordan/Network-Connectivity

### LINKED ISSUE #1322: move network connectivity bar to sidebar to match design

### PR DESCRIPTION
**Pull request by jbibla**
Closes #1322 

thanks @NodeGuy for the help with the tests

### CODE REVIEW

**Comment by fedekunze** [comment]
what is this PR about ?

**Comment by jbibla** [comment]
screen shot 2018-09-28 at 12 06 13 pm
screen shot 2018-09-28 at 12 06 20 pm
screen shot 2018-09-28 at 12 06 31 pm

**Comment by jbibla** [comment]
as part of an effort to communicate trust and security.

when we implement https://github.com/cosmos/voyager/issues/1222 we can show this info in the tooltip on the lock.

screen shot 2018-10-01 at 8 59 56 am

screen shot 2018-10-01 at 8 54 55 am

**Comment by faboweb** [comment]
When would this show an open lock?

**Comment by faboweb** [comment]
So the icon has no purpose right now? As with code, should we maybe avoid implementing things we don't need yet?

**Comment by faboweb** [comment]
I don't have the feeling that this symbol shows a "connection" maybe a "secure connection". But I don't feel strongly about it.

**Pull request merged**
