### PR TITLE
WIP: Add shell script diagnostics to testnets build script.

### LINKED ISSUE #1126: Downloading testnet config script doesn't work
UI Version: 0.9.4

Description:

Running `yarn build:testnets` doesn't generate any testnet files in `./builds/testnets`

### PR DESCRIPTION
**Pull request by NodeGuy**
Closes #1126

Description:

❤️ Thank you!

### CODE REVIEW

**Comment by faboweb** [comment]
I pushed a solution proposal. Can you verify this works? And maybe explain to me, why it works this way? ^^

**Comment by NodeGuy** [comment]
That is SUPER mysterious!  We're running in Docker so shouldn't be getting a "works on my machine" error like this.  I can't think of any hypothesis that explains the problem.  Your workaround is not a good one and should be unnecessary.

Please try collaborating with someone local (Billy or Fede) and see if they notice anything, otherwise we can schedule a meeting to debug it together.

**Comment by faboweb** [comment]
> Your workaround is not a good one and should be unnecessary.

Can you elaborate why this is a bad solution?

**Comment by NodeGuy** [comment]
Closed in favor of https://github.com/cosmos/voyager/pull/1176.

**Pull request closed without merging**
