### PR TITLE
peng/create-blog

### PR DESCRIPTION
**Pull request by nylira**
Closes: #577

Created the first blog post for our bi-monthly Voyager Update for the Cosmos Blog. Feedback appreciated! I know that we should add more details about David. @NodeGuy is there anything you want to have highlighted about you?

- [x] create first blog post

### CODE REVIEW

**Comment by nylira** [comment]
>Could you branch this off of develop? Nice that you already got to it. I personally would like less off a status update more of a inside into work. Like technical or design topics. But we can discuss this tonight.

Yes, I agree that we could use regular "Designing for Cosmos" or "UI Architecture for Cosmos" blog posts. Perhaps 1-2 of them a month. But twice a month with status updates is also nice to have, especially the past month or two when we haven't been able to make a full point release. Also, the former take far more time to write. =)

**Comment by nylira** [comment]
I think this is ready to go, unless someone has ideas for improving the first post. We could use a header graphic!

**Comment by nylira** [comment]
voyager-update-2018-03-20

**Comment by NodeGuy** [comment]
>  @NodeGuy is there anything you want to have highlighted about you?

Thanks, it might be fun to mention that I previously worked at Monax.

**Pull request merged**
