### PR TITLE
I wanna lint lint lint

### PR DESCRIPTION
**Pull request by sabau**
**Description:**
- Slowly adding missing rules
- not all the necessary rules are already here, it's a process

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by sabau** [comment]
That's funny XD coverage missing after linting

**Comment by jbibla** [comment]
@sabau is your plan to fix and revive this PR or should we close for now?

**Comment by jbibla** [comment]
@sabau ping ping ping

**Comment by jbibla** [comment]
closing because no response

**Pull request closed without merging**
