### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by faboweb**
> Thank you a lot for contributing to Cosmos Voyager!

### Issue

closes: 513

❤️ Thank you!

### CODE REVIEW

**Comment by jolesbi** [comment]
excellent improvements fabo. this is great. 

gaia is deprecated - but i'll merge for now and we can update again when the SDK is a bit more clear about gaia.

**Comment by faboweb** [comment]
perfect. this was also my intention. thank you for clarifying

**Comment by NodeGuy** [comment]
Hold on cowboy, you've got updates here for Docker that aren't applicable yet because the Docker PR hasn't been merged.  Now I've got merge conflicts to sort through.

**Comment by faboweb** [comment]
You are right @NodeGuy . I should have paid more attention to this and added a note in the description. I will pay more attention in the future.

**Pull request merged**
