### PR TITLE
Make command line programs behave better during exceptions.

### PR DESCRIPTION
**Pull request by NodeGuy**
There was some boilerplate code in our CLI tools that looked like this:

```JavaScript
main().catch(reason => {
  console.error(reason)
  process.exit(1)
})
```

This PR adds the above code to the CLI argument parsing library used by some of the tools.

### CODE REVIEW

**Comment by faboweb** [comment]
Could you give a little more insight about what the problem was and how the new version fixes it?

**Comment by faboweb** [comment]
+ please do not skip push hooks, you missed the changelog update again ;P

**Comment by NodeGuy** [comment]
> Could you give a little more insight about what the problem was and how the new version fixes it?

Done.

**Comment by faboweb** [comment]
Is it correct that there is no code change on our side then?

**Comment by NodeGuy** [comment]
Correct and I don't have permission to merge.

**Pull request merged**
