### PR TITLE
add specs for update method and value watcher

### LINKED ISSUE #1774: TmFieldSeed.spec.js-update-to-100%-coverage
UI Version: 0.X.X

Description:

proposal:

adding tests for the update method and the value watcher - brings coverage for this file to 100%
added a debug:test script

### PR DESCRIPTION
**Pull request by coreycosman**
Closes #1774 

_Description:_

added specs for update method and value watcher- test coverage to 100% for this file. 

❤️ Thank you!

---

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

**Comment by jbibla** [comment]
i messaged him - he may be travelling / on vacation.

**Comment by fedekunze** [comment]
unit tests failing

**Comment by faboweb** [comment]
E2E tests are sometimes unreliable because of async problems. If your unit tests run fine, I will make the PR pass.

**Comment by coreycosman** [comment]
Yea all tests are running fine

**Comment by faboweb** [comment]
Unit tests are broken:
https://circleci.com/gh/cosmos/voyager/13966

**Comment by coreycosman** [comment]
please see my most recent PR

**Comment by fedekunze** [comment]
I will close this then, let's use the other PR

**Pull request closed without merging**
