### PR TITLE
billy/1108-small-text

### LINKED ISSUE #1108: available balance shows in small font for a few seconds
UI Version: 0.9.3

Description:

screen shot 2018-08-08 at 1 42 28 pm

To reproduce this I log out and I log in again.  The font is small for a few seconds and then fixes itself.

### PR DESCRIPTION
**Pull request by okwme**
Closes #1108 

Description: hinges on https://github.com/tendermint/ui/pull/57 where the transition has been removed from tm-li component

❤️ Thank you!

### CODE REVIEW

**Comment by okwme** [comment]
can be reviewed already but should note that actually blocked by publishing new version of tendermint/ui (https://github.com/tendermint/ui/pull/57)

**Comment by faboweb** [comment]
Webpack doesn't seem to use the internal assets in the UI library. :/

**Comment by okwme** [comment]
working again but blocked by official release of https://github.com/tendermint/ui/issues/60

**Comment by faboweb** [comment]
@NodeGuy just a note: there are still conflicts on the changelog

**Comment by faboweb** [comment]
@okwme this is still failing

**Comment by okwme** [comment]
thanks @faboweb idk how i typed in the wrong version so many times 🙄
checking the test coverage now and hopefully ready v soon

**Comment by okwme** [comment]
@faboweb codecov is ok!

**Comment by faboweb** [comment]
Happens to the best. ;)

**Pull request merged**
