### PR TITLE
added prettier precommit hook

### PR DESCRIPTION
**Pull request by faboweb**
Source: https://prettier.io/

Will always apply prettier to every commit. No more `linted` commits!

### CODE REVIEW

**Comment by NodeGuy** [comment]
Good idea.  Do you use an [editor plugin](https://prettier.io/docs/en/editors.html)?  I never need to run it manually because my editor does it automatically on saves.

**Comment by faboweb** [comment]
I do, but sometimes in some configurations it doesn't format it the same way. :/ Which causes me to get back and forth in some PRs. This should solve this.
But I am not feeling too strongly about it.

**Comment by nylira** [comment]
I think we should do this. The easier it is for developers to contribute (without forcing them to install Prettier) the better.

**Comment by faboweb** [comment]
Feel free to approve and merge

**Comment by nylira** [comment]
Changelog needs an update!

**Pull request merged**
