### PR TITLE
Fabo/show connection infos

### PR DESCRIPTION
**Pull request by faboweb**
Added information about the current connection as the addressbook might attempt to connect to a lot of offline nodes in some cases.

Video:
out

❤️ Thank you!

### CODE REVIEW

**Comment by faboweb** [comment]
Sorry for the bad screencast :D anyone has nice tooling for that?

**Comment by jolesbi** [comment]
can you also share a static screenshot? i can't tell what i'm supposed to be reviewing 🎥😆

**Comment by faboweb** [comment]
This is the initial "Loading..." view before the login screen.

**Comment by faboweb** [comment]
image

**Comment by okwme** [comment]
hard to test without a testnet. using localnode i connect, using localnode without actually running localnode i hang on "connecting to 'gaia-6002'" without any ip addresses. Maybe good to have a final message when you run out of ip addresses to try?

**Comment by okwme** [comment]
ah it did work! forgot that testnet is up just no new blocks coming in

**Pull request merged**
