### PR TITLE
WIP: Update validators when they change

### LINKED ISSUE #946: Update the validators when they change
UI Version: 0.7.1

Description:

Currently the validators are loaded once via the LCD. It would be nice to update them every time they change so the user sees the live validator set.

### PR DESCRIPTION
**Pull request by fedekunze**
Closes #946 

Description:

Subscribes to new tendermint event `tm.event='ValidatorSetUpdates'`.
Blocked by [tendermint/2161](https://github.com/tendermint/tendermint/pull/2161), which is blocked by [tendermint/2159](https://github.com/tendermint/tendermint/pull/2159). 

❤️ Thank you!

### CODE REVIEW

**Comment by jbibla** [comment]
24 days old?

giphy-3 2

**Comment by faboweb** [comment]
As discussed in the team meeting this is waiting for a new Tendermint version to be merged into the SDK.

**Comment by jbibla** [comment]
can we close this or are we waiting for new tendermint version?

i smell a lot of conflicts on the horizon 👃

**Comment by fedekunze** [comment]
@jbibla you're right. Although we already have this logic by manually checking the validator set changes on each block. I'd vote to close it and do a later refactor by introducing an observer/subscribe design pattern.

**Comment by jbibla** [comment]
sounds good. @faboweb what do you think?

**Comment by faboweb** [comment]
There are no conflicts as of right now. I don't get what changed since we decided to keep this PR. But if you want to redo the work, feel free to close this.

**Comment by NodeGuy** [comment]
So @fedekunze shall we close this?

**Pull request closed without merging**
