### PR TITLE
Return-to-sender bot

### LINKED ISSUE #773: Mock server: Have "bot" that sends you money back
UI Version: 0.6.2.

Description:

To test sending and receiving coins to and from another address, it would be nice to have a tutorial that tells you to send to some address (of a bot) that sends you money back. (This could even be a thing on the actual network o.O)

- [x] add auto send back functionality to mock server
- [x] add tutorial about the send back functionality

### PR DESCRIPTION
**Pull request by mappum**
Closes #773 

This implements the bot and fixes tx history for mocked mode.

TO DO:
- [x] For some reason, these changes made the mocked timestamps change in unrelated tests 
- [x] Implement a tutorial explaining the bot (I'm not really sure the best way to do that)

### CODE REVIEW

**Comment by faboweb** [comment]
For the tutorial: Maybe just show a message in mocked mode on the sendpage?

**Comment by mappum** [comment]
Added a message about the bot address to `PageSend` when in mocked mode. LMK if I should reword or restyle it:

**Comment by mappum** [comment]
I could use some assistance figuring out why all the timestamps changed in the tests, seems strange since I didn't touch any of that code.

**Comment by faboweb** [comment]
Fixed tests

**Comment by faboweb** [comment]
Coverage for PageTransactions.vue can be ignored.
Coverage for send.js should be improved.

**Pull request merged**
