### PR TITLE
billy/ 521 Consistent Search

### LINKED ISSUE #521: Make search consistent
> Thank you for filing an issue!

### Version

0.4.3

### Description

For consistency every top level page should have a search functionality.

### PR DESCRIPTION
**Pull request by okwme**
Closes #521 

Description:
made search consistent as per @jolesbi recommendations on #521  

❤️ Thank you!

### CODE REVIEW

**Comment by okwme** [comment]
@jolesbi bless u for the bump! 

yours didn't pull us out of the red tho did it? was also surprised mine was in red after the first fail and the subsequent beefing that already took place...

**Comment by jolesbi** [comment]
i wanted to get it in! but no, i couldn't get it through... seems very strange to me.

**Comment by faboweb** [comment]
Could you improve the coverage for PageBlocks, PageTransactions, PageStaking (probably copy pasting the test for somethingToSearch)?

**Comment by okwme** [comment]
the only thing not covered in PageBlocks, PageTransactions or PageStaking is Mousetrap. We shouldn't be testing that tho, right?

PageBlocks:  
screenshot 2018-05-30 15 25 38
PageTransactions : 
screenshot 2018-05-30 15 26 42
PageStaking:  
screenshot 2018-05-30 15 27 16

**Comment by jolesbi** [comment]
> Could you improve the coverage for PageBlocks, PageTransactions, PageStaking (probably copy pasting the test for somethingToSearch)?

i did that here 1ff25d1

**Comment by faboweb** [comment]
Very good PR. :)

**Pull request merged**
