### PR TITLE
Redirecting dependency to cosmos repo

### LINKED ISSUE #2031: Direct package.json to cosmos repo
**Describe the bug**
Now that cosmos-ledger-js has been forked by `cosmos`.
We should replace ZondaX by cosmos here:

https://github.com/cosmos/voyager/blob/de6d76f6ea4147f776188358c35ca7d47db341f8/package.json#L133

That will simplify issue tracking, etc.
@jackzampolin @fedekunze

### PR DESCRIPTION
**Pull request by jleni**
Closes #2031 

**Description:**

Now voyager will point directly to cosmos/ledger-cosmos-js

---

For contributor:

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
Could you please update the changelog?

**Comment by jleni** [comment]
> Could you please update the changelog?

yep, I was just doing that! :)

**Comment by faboweb** [comment]
Sorry, hahahhaha I was too quick. Thanks for this PR! :)

**Comment by jbibla** [comment]
thank you @jleni!

**Pull request merged**
