### PR TITLE
Fabo/added feedback btn

### PR DESCRIPTION
**Pull request by faboweb**
Adds a feedback button for a user feedback collection service: https://www.appzi.com

image
image

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by fedekunze** [comment]
hmmm although I like the idea of the feedback, this design doesn't match at all with our current theme.  Thoughts @jbibla ?

**Comment by fedekunze** [comment]
also a submodule was added ? is that on purpose ?

**Comment by faboweb** [comment]
> also a submodule was added ? is that on purpose ?

nop, will remove it

**Comment by jbibla** [comment]
> this design doesn't match at all with our current theme. 

i will try to change the color and font family - but this is a quick and easy way to try and get some feedback. an experiment of sorts - so i am ok with this in the short term.

**Comment by faboweb** [comment]
The colors used are our primary color and our secondary color ;)

**Pull request merged**
