### PR TITLE
Fabo/774 upload e2e screenshot

### PR DESCRIPTION
**Pull request by faboweb**
Implements part of #774

Description:

Stores the screenshot of a failed e2e test as an artifact.
image

❤️ Thank you!

### CODE REVIEW

**Comment by okwme** [comment]
looks good to me. we need an artificial error to test it tho right?

**Comment by faboweb** [comment]
I did produce one here: https://circleci.com/gh/cosmos/voyager/3042#artifacts/containers/0

**Comment by okwme** [comment]
oh awesome, how can i look on the circle server to see the screenshot and log?

**Comment by faboweb** [comment]
Only the screenshot for now. Log should already be in the console but I will also add it to the artifacts in a later step.
If you click the link, there is a tab "artifacts" this will hold the screenshot after a failure.

**Comment by okwme** [comment]
closes #780

**Comment by okwme** [comment]
closes #774

**Comment by NodeGuy** [comment]
Nice.

**Pull request merged**
