### PR TITLE
Fabo/1993 disable web wallet

### LINKED ISSUE #1993: Disable web wallet in production
UI Version: 0.X.X

Description:

We agreed to not show the web wallet features in production as it is not considered safe.

AC:
- [ ] disable key import
- [ ] disable key create
- [ ] disable sign in with local key

### PR DESCRIPTION
**Pull request by faboweb**
Closes #1993 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
please make sure you add an option to "use voyager in explorer mode" so the session modal has more than 1 option!

**Comment by jbibla** [comment]
also, please remove the two paragraphs about fundraiser seeds as this is no longer relevant.

**Comment by fedekunze** [comment]
screenshots ? 😄

**Comment by faboweb** [comment]
thx for pointing that out @fedekunze

**Comment by faboweb** [comment]
image

**Pull request merged**
