### PR TITLE
Reapply staking refactoring

### LINKED ISSUE #879: Staking sections self DDoSes
UI Version: 0.7.0

Description: Polling each validator for amount of user's stake DDoSes the LCD and often crashes gaia causing a reconnect. This happens on mounted event for the staking page as well as wallet page with the action `updateDelegates`.

### PR DESCRIPTION
**Pull request by faboweb**
Closes #879, #355, #1102 

Description:

❤️ Thank you!

### CODE REVIEW

**Comment by faboweb** [comment]
Wait for gaia-8000

**Comment by fedekunze** [comment]
@faboweb does this addresses #1042 as well ?

**Comment by faboweb** [comment]
I think yes. We refactored the staking endpoints so that there is not "fractions" anymore. It is just floating point numbers delivered from the LCD.

**Comment by faboweb** [comment]
As discussed with Billy I reapply these changes now. They will not work with Gaia-7005!

**Pull request merged**
