### PR TITLE
Fabo/2089 changed devmode flag to insecure

### LINKED ISSUE #2089: Rename devMode url flag to insecure

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2089 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
change the html too!

**Comment by faboweb** [comment]
You mean the "Development Mode" warning?

**Comment by fedekunze** [comment]
don't we need to change also the features that are on `devMode` ?

**Comment by fedekunze** [comment]
I think we should keep the development mode, I don't see why for eg using ledger on dev mode can be insecure

**Comment by jbibla** [comment]
> I don't see why for eg using ledger on dev mode can be insecure

it wouldn't be. are you concerned it will be misleading?

**Comment by fedekunze** [comment]
@jbibla yes indeed

**Comment by fedekunze** [comment]
I'd kill this PR, devMode assumes it's insecure

**Comment by jbibla** [comment]
> devMode assumes it's insecure

i really don't think this is true. devMode could imply all kinds of things, like we're in a semi-stable-beta, or we're displaying experimental features that have nothing to do with security.

IMO we need a feature flag (which we can call devMode) and we need an insecure flag (for using seeds / passwords on the web).

> I don't see why for eg using ledger on dev mode can be insecure

this could be misleading and i agree with you there. can we only display the insecure mode banner when the user has signed in with a seed or a password?

**Comment by faboweb** [comment]
So you want 2 flags? `experimental` and `insecure`?

**Comment by jbibla** [comment]
> So you want 2 flags? `experimental` and `insecure`?

i think this would be ideal but we don't need this now. i don't think we have features that need to be flagged that aren't insecure.

**Comment by faboweb** [comment]
Switched to `experimental` as the flag name and updated the position of the warning on smaller screens a little

image

**Comment by jbibla** [comment]
@faboweb i'm sorry! i think i was misunderstood. i think it is really important that it says insecure. if we want a dev / experimental flag we could add that too at a later date.

**Comment by jbibla** [comment]
> devMode is a place where you can play with code, literally development, so in a bundled environment 
I will expect not to find a flag with that name/meaning.

@sabau does this mean you don't think we should use `devMode` at all?

---

sorry to be strong about this - but i think it's important that we show "insecure mode" for when the password or seeds are going to be in the browser.

**Comment by faboweb** [comment]
Updated

**Pull request merged**
