### PR TITLE
Peng billy/669 preferences page

### PR DESCRIPTION
**Pull request by okwme**
Closes #ISSUE #669 

Description: we updated the profile page to a preferences page with a new layout to accomodate for the new content. I forked peng's vue-field component to include a toggle. the repo points to my fork until peng accepts my PR

screenshot 2018-05-29 16 36 20

❤️ Thank you!

### CODE REVIEW

**Comment by nylira** [comment]
Looks good! The design of the toggle does stick out a bit. Let's make some changes.

* We don't need a label in the toggle. On or off should be obvious to the user with a background color for "on".
* Let's make it a little less wide.
* The scrubber for the toggle shouldn't be so dark.

I can do these changes tomorrow, or you can do it @okwme if you want. Will merge the PR into @nylira/vue-input tomorrow too.

**Comment by jolesbi** [comment]
> We don't need a label in the toggle. On or off should be obvious to the user with a background color for "on".

green and red can be used to help

i just noticed the buttons are quite skinny too - is this on purpose?

**Comment by okwme** [comment]
anyone know why these test are failing on circle and not when run locally?
The words in the toggle can be removed in the options. without them the toggle becomes smaller too. i've just replaced them and also added some margins, not sure if they help tho...

**Comment by jolesbi** [comment]
```
logging into default
unhandledRejection { Error: element ("#sign-in-name select") still not existing after 10000ms
    at new WaitUntilTimeoutError (/home/circleci/repo/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:150:12)
    at /home/circleci/repo/node_modules/webdriverio/build/lib/commands/waitUntil.js:29:19
    at <anonymous>
  details: undefined,
  message: 'element ("#sign-in-name select") still not existing after 10000ms',
  type: 'WaitUntilTimeoutError' }
saving screenshot to  /home/circleci/repo/test/e2e/snapshot.png
```

**Comment by jolesbi** [comment]
`yarn test:e2e` fails locally for me

**Comment by okwme** [comment]
light:
screenshot 2018-05-30 18 02 18 screenshot 2018-05-30 18 02 25 
dark:
 screenshot 2018-05-30 18 02 41 screenshot 2018-05-30 18 02 34 
action shot:
screenshot 2018-05-30 18 02 44 screenshot 2018-05-30 18 02 50

**Comment by jolesbi** [comment]
love the actions shots

**Comment by nylira** [comment]
Linting, e2e, and unit tests all work locally:

```
BINARY_PATH=$GOPATH/bin/gaiacli yarn test
``

Something is messed up with our CircleCI.

**Comment by nylira** [comment]
@jolesbi `BINARY_PATH=$GOPATH/bin/gaiacli yarn test` runs for me locally.

**Comment by nylira** [comment]
@jolesbi the buttons are wider than usual on purpose. I thought that setting the button width to equal the input looks better visually, following a grid.

**Comment by faboweb** [comment]
Found a bug:
The network selector always starts with 'Live Network' even if started in mocked mode.

**Comment by okwme** [comment]
@jolesbi @faboweb would you maybe check these too to see if @jolesbi right and it's the binary to blame for the circle tests?
```
sha256sum gaiacli-0.17.0-ubuntu
bcb88084a55875d1707231f9fc4ef19fdc4cc3defcb130acb51fa3415f407cf2  gaiacli-0.17.0-ubuntu
sha256sum gaiad-0.17.0-ubuntu
42818bcd0c3e02e548c92871cf8677e22a3216edacc5ac162b800744f3c31c7d  gaiad-0.17.0-ubuntu
```

**Comment by faboweb** [comment]
I am pretty sure it is not the binary. Logging in already passed before. The issue appears only after switching to the mocked connector.

**Comment by okwme** [comment]
got the bug @faboweb nice catch 🐞

**Comment by faboweb** [comment]
So the problem is, it doesn't really logout.

**Comment by faboweb** [comment]
The network switch is fixed. Now a test fails because it doesn't correctly check a checkbox.

**Comment by nylira** [comment]
```
TAP version 13
# preferences
using cli binary /Users/pz/go/bin/gaiacli
using node binary /Users/pz/go/bin/gaiad
ui home: /var/folders/v3/yzp94ctx4dzdzcnvt1q4_7qm0000gn/T/8suzom1895x
node home: /var/folders/v3/yzp94ctx4dzdzcnvt1q4_7qm0000gn/T/blau6kh90fp
/Users/pz/go/bin/gaiad start --home /var/folders/v3/yzp94ctx4dzdzcnvt1q4_7qm0000gn/T/blau6kh90fp
Started local node.
unhandledRejection Error: ChromeDriver did not start within 10000ms
    at /Users/pz/Projects/voyager/node_modules/spectron/lib/chrome-driver.js:63:25
    at Request._callback (/Users/pz/Projects/voyager/node_modules/spectron/lib/chrome-driver.js:120:23)
    at self.callback (/Users/pz/Projects/voyager/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.onRequestError (/Users/pz/Projects/voyager/node_modules/request/request.js:878:8)
    at ClientRequest.emit (events.js:160:13)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at Socket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
pz@mbp ~/P/voyager> yarn
yarn install v1.7.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
✨  Done in 4.82s.
```

Is this the `yarn test:e2e` error everyone is getting?

**Comment by faboweb** [comment]
Nope ;) Try reinstalling the dependencies. Billy also had problems with a newer Chrome version before. I am currently investigating the failing tests.

**Pull request merged**
